### ISSUE TITLE
IOS problem

### ISSUE THREAD

**Issue by kgoedert** [lucasferreira/react-native-flash-message#89]
Hello,

My project is using react-native 0.61.5 and react-native-flash-message": "^0.1.15". On the android emulator it works fine but when I try to run my project on ios emulator, I get the following error:

```
Unable to resolve module `/usr/local/lib/node_modules/react-native/Libraries/Image/AssetRegistry` from `node_modules/react-native-flash-message/src/icons/fm_icon_success.png`:

None of these files exist:
  * ../../../../usr/local/lib/node_modules/react-native/Libraries/Image/AssetRegistry(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * ../../../../usr/local/lib/node_modules/react-native/Libraries/Image/AssetRegistry/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at dependencies.map.result (/usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/local/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```
what am I missing?

**Comment by kgoedert** [comment]
It was a cache problem. Restarted everything, npm, xcode,... and it worked
